name: 'Infra API'

on:
  push:
    branches: [ "release", "main" ]

permissions:
  contents: read

jobs:
    Terraform:
        name: 'Terraform - Create Infra'
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./terraform
            shell: bash

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: sa-east-1

        - name: Verificando se bucket 'tfstate-grupo12-fiap-2025' está criado
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: |
              BUCKET_NAME="tfstate-grupo12-fiap-2025"
              REGION="sa-east-1"
          
              if ! aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
                echo "Bucket não existe. Criando bucket..."
                aws s3api create-bucket --bucket "$BUCKET_NAME" --create-bucket-configuration LocationConstraint="$REGION"
              else
                echo "Bucket validado."
              fi
          
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
    
        - name: Terraform Init
          run: terraform init

        - name: Terraform Format
          run: terraform fmt -check

        - name: Terraform Plan
          run: terraform plan -input=false

        - name: Terraform Apply
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false